sudo: required

language: generic

services:
  - docker

env:
  global:
    - target_version=0.17.0
    - target_platform=linux
    - qemu_version=4.0.0
  matrix:
    - target_arch=arm64 qemu_arch=x86_64
    - target_arch=armv7 qemu_arch=arm
    - target_arch=armv6 qemu_arch=arm
    - target_arch=amd64 qemu_arch=aarch64

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo service docker restart
  - mkdir bin

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - curl -sLO https://github.com/multiarch/qemu-user-static/releases/download/v${qemu_version}/qemu-${qemu_arch}-static.tar.gz;
  - tar -xzvf qemu-${qemu_arch}-static.tar.gz;
  - curl -sLO https://github.com/prometheus/alertmanager/releases/download/v${target_version}/sha256sums.txt
  - curl -sLO https://github.com/prometheus/alertmanager/releases/download/v${target_version}/alertmanager-${target_version}.${target_platform}-${target_arch}.tar.gz;
  - if [ ! -z $(sha256sum -c sha256sums.txt 2> /dev/null | grep OK) ]; then
      tar -xzvf alertmanager-${target_version}.${target_platform}-${target_arch}.tar.gz;
      cd alertmanager-${target_version}.${target_platform}-${target_arch};
      cp alertmanager.yml ../conf/alertmanager_${target_arch}.yml;
      cp alertmanager ../bin/alertmanager_${target_arch};
      cp amtool ../bin/amtool_${target_arch};
      cd ..;
    fi;
  - rm alertmanager-${target_version}.${target_platform}-${target_arch}.tar.gz;
  - rm -rf alertmanager-${target_version}.${target_platform}-${target_arch};
  - rm sha256sums.txt
  - docker build -f Dockerfile.${target_arch} -t ndanyluk/alertmanager-${target_arch}:$TRAVIS_BUILD_NUMBER .

after_success:
  - if [ -z "$DOCKER_USER" ]; then
      echo "PR build, skipping Docker Hub push";
    elif [ "$TRAVIS_BRANCH" != "master" ]; then
      echo "Branch build, skipping Docker Hub push";
    else
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
      docker tag ndanyluk/alertmanager-${target_arch}:$TRAVIS_BUILD_NUMBER ndanyluk/alertmanager-${target_arch}:${target_version};
      docker tag ndanyluk/alertmanager-${target_arch}:$TRAVIS_BUILD_NUMBER ndanyluk/alertmanager-${target_arch}:latest;
      docker push ndanyluk/alertmanager-${target_arch}:${target_version};
      docker push ndanyluk/alertmanager-${target_arch}:latest;
    fi
